server:
  port: 9015


app:
  zk:
    addr: 127.0.0.1:2181
    connect:
      timeout: 15000
#   Registered root node
    root: /route
  route:
    method: com.yuge.yimcommon.route.algorithm.random.RouteHandle


spring:
  redis:
    host: 127.0.0.1
    port: 6379
