server:
  port: 9010

# unique account of the Client
yim:
  client:
    userId: 982287281
    userName: SingleCycle
    reconnect:
      count: 3

  route:     # route url suggested that this is Nginx address
    url: http://localhost:8083/